workspace:

  base: /build

pipeline:

  relay:
    image: node:lts-alpine
    commands:
      - mkdir build_results
      - cd spacerelay
      - npm install
      - tar cvpzf ../build_results/relay.tgz .

  widget:
    image: python:3-alpine
    commands:
      - cd spacewidget
      - pip install setuptools wheel
      - python3 setup.py sdist bdist_wheel
      - mv dist/spacewidget-*.whl ../build_results/

  release:
    image: plugins/gitea-release
    base_url: https://git.core.bckspc.de
    secrets: [ gitea_token ]
    files: build_results/*
    when:
      event:
        - tag

  git:
    image: plugins/git-push
    secrets:
      - target: GIT_PUSH_SSH_KEY
        source: github
    remote: git@github.com:foosinn/spacewidget.git
    branch: master
    force: true

  gitrelease:
    image: plugins/github-release
    secrets: [ github_token ]
    files: build_results/*
    when:
      event:
        - tag

  pypi:
    image: gjtempleton/drone-pypi
    repository: https://upload.pypi.org/legacy/
    username: foosinn
    secrets:
      - target: PLUGIN_PASSWORD
        source: pypi
    setupfile: spacewidget/setup.py

  npm:
    image: plugins/npm
    username: foosinn
    email: npm@f2o.io
    secrets:
      - target: PLUGIN_TOKEN
        source: npm
    folder: spacerelay
